name: Deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Dev
        run: flyctl deploy --remote-only --config ./fly.dev.toml --dockerfile ./Dockerfile.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
