name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Production
        run: flyctl deploy --remote-only --config ./fly.prod.toml --dockerfile ./Dockerfile.prod
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
